### ISSUE TITLE
Hiking routes symbols shown as white boxes

### ISSUE THREAD

**Issue by hayvan96** [Hades1503/OsmAnd_Hiking_Map#10]
Hi

since the upgrade to 4.2.x, Osmand has changed the way theyr render (hiking routes).
See here https://osmand.net/blog/osmand-android-4-2-released#routes-on-the-map

When using this render, affiliation boxes (the names of the routes) are shown as empty boxes. When using topo or uniRS, it's OK.

Known issue? I prefer your XML as it's very legible and close to IGN style.

**Comment by Hades1503** [comment]
bonjour, 
c'est corrigé

**Comment by hayvan96** [comment]
Merci. But with the new version, osmand crashes (4.2.6), have you tested it?

**Comment by Hades1503** [comment]
> Merci. But with the new version, osmand crashes (4.2.6), have you tested it? 
> 
> 
> 
> Edit: attaching the crash log. Do you want me to reopen an issue? 
> 
> [exception.log](https://github.com/Hades1503/OsmAnd_Hiking_Map/files/9079533/exception.log)
> 
> 


it's good now
