### ISSUE TITLE
Render theme alike to mapy.cz

### ISSUE THREAD

**Issue by Trojgarb** [Hades1503/OsmAnd_Hiking_Map#8]
Hello, as a user of mapy.cz app I would like to ask whether it's possible to create a render theme for Osmand in order to achieve the look of their map? Mapy.cz has IMO the best hiking/cycling rendering theme of all navigation apps, however the app alone is quite primitive and lacks many features the Osmand has. It would be great to have the best app (Osmand) with the nicest outdoor theme mapy.cz offer. :)

**Comment by Hades1503** [comment]
Hello, 
I agree with you. Unfortunately, creating a map rendering like mapy.cz is not possible (for routes or rendering). 
However, you will find yourself on anygis.ru the online maps of mapy.cz. If you put it on a main map you will be able to download the area you are interested in as well as select the zooms for offline consultation.
